//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suntek.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SuntekEntities : DbContext
    {
        public SuntekEntities()
            : base("name=SuntekEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Brandname> Brandname { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<District> District { get; set; }
        public virtual DbSet<PieName> PieName { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductActive> ProductActive { get; set; }
        public virtual DbSet<ProductAgent> ProductAgent { get; set; }
        public virtual DbSet<ProductWarranti> ProductWarranti { get; set; }
        public virtual DbSet<Province> Province { get; set; }
        public virtual DbSet<SendMT> SendMT { get; set; }
        public virtual DbSet<TempBrandname> TempBrandname { get; set; }
        public virtual DbSet<TemplateMT> TemplateMT { get; set; }
        public virtual DbSet<TempSms> TempSms { get; set; }
        public virtual DbSet<Ward> Ward { get; set; }
        public virtual DbSet<Article> Article { get; set; }
        public virtual DbSet<Banner> Banner { get; set; }
    }
}
