//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suntek.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempSms
    {
        public string Id { get; set; }
        public string Command_Code { get; set; }
        public string Hotline { get; set; }
        public Nullable<int> ActiveSms { get; set; }
        public Nullable<int> MsgType { get; set; }
        public Nullable<int> ActiveByAgent { get; set; }
    }
}
